name: API Quality Control

defaults:
  run:
    shell: bash
    working-directory: ./backend

on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened, ready_for_review]
    # paths:
    #   - "server/api/**/*.py"
    #   - "server/poetry.lock"
    #   - "server/pyproject.toml"

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Run Tox (lint)
        run: poetry run tox -e lint

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Run Tox (security)
        run: poetry run tox -e security

  pytest:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Run Tox (pytest)
        run: poetry run tox -e pytest
      # - name: Code Coverage Summary Report
      #   uses: irongut/CodeCoverageSummary@v1.3.0
      #   with:
      #     filename: ./backend/coverage.xml
      #     badge: true
      #     fail_below_min: true
      #     format: markdown
      #     indicators: true
      #     output: both
      # - name: Add Coverage PR Comment
      #   uses: marocchino/sticky-pull-request-comment@v2
      #   with:
      #     recreate: true
      #     path: code-coverage-results.md
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
